### ISSUE TITLE
Define .snyk ignore content

### ISSUE THREAD

**Issue by jeremiahjstacey** [ESAPI/esapi-java-legacy#629]
SNYK tool continues to report the upgrade of commons-io.  We cannot support that and maintain Java 7 compatibility.  Looking through the SNYK documentation, we should be able to generate a .snyk file and specify an ignore clause and a reason for ignore, which should prevent the tool from flagging the version going forward.
https://github.com/ESAPI/esapi-java-legacy/pull/627
https://snyk.io/vuln/SNYK-JAVA-COMMONSIO-1277109

Based on the SNYK documentation [here](https://support.snyk.io/hc/en-us/articles/360007487097-The-snyk-file), I think the .snyk file should contain approximately what I've outlined below.

```
# Snyk (https://snyk.io) policy file, patches or ignores known vulnerabilities.
version: v1.14.0
ignore:
 SNYK-JAVA-COMMONSIO-1277109:
    - commons-io:commons-io:
        reason: ESAPI cannot upgrade past the current commons-io version and still maintain Java 7 compatibility
        expires: '2025-12-30T00:00:00.000Z'
```

I am not entirely sure how to test this content without waiting to see if SNYK flags commons-io on its next pass.
